<?php

namespace App\Filament\App\Resources\Attendees\Widgets;

use App\Filament\App\Resources\Attendees\Pages\ListAttendees;
use App\Models\Attendee;
use Filament\Widgets\Concerns\InteractsWithPageTable;
use Filament\Widgets\StatsOverviewWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class AttendeesStatsWidget extends StatsOverviewWidget
{
    use InteractsWithPageTable;

    protected function getTablePage(): string
    {
        return ListAttendees::class;
    }

    protected function getColumns(): int|array|null
    {
        return 2;
    }

    protected function getStats(): array
    {
        $query = $this->getPageTableQuery();
        $sum = $query->orders = [];
        return [
            Stat::make('Attendees Count', $query->count())
                ->description('Total number of attendees')
                ->descriptionIcon('heroicon-o-user-group')
                ->color('success')
                ->chart([1,2,3,4,5,6,4,1,1,2]),
            Stat::make('Total Revenue', $query->sum('ticket_cost'))
                ->description('Total revenue generated by attendees')
        ];
    }
}
